[package]
name = "fat32"
version = "0.1.0"
authors = ["Me <user@rust-lang.org>"]

[dependencies]
sha2 = "0.8.2"
clap = { version = "3.1.18", features = ["derive"] }
libc = "0.2"
rand = "0.7.3"
log = "0.4.17"
env_logger = "0.9.0"
